//// Code generated by parrot. DO NOT EDIT.
////

import gleam/dynamic/decode
import gleam/option.{type Option}
import parrot/dev

pub type ListAllUsers {
  ListAllUsers(name: String)
}

pub fn list_all_users(name name: String) {
  let sql =
    "SELECT name
FROM users
WHERE name = ?"
  #(sql, [dev.ParamString(name)], list_all_users_decoder())
}

pub fn list_all_users_decoder() -> decode.Decoder(ListAllUsers) {
  use name <- decode.field(0, decode.string)
  decode.success(ListAllUsers(name:))
}

pub type InsertUser {
  InsertUser(name: String)
}

pub fn insert_user(name name: String) {
  let sql =
    "INSERT
INTO users
  (
    name
  )
VALUES
  (
    ?
  )
RETURNING
  name"
  #(sql, [dev.ParamString(name)], insert_user_decoder())
}

pub fn insert_user_decoder() -> decode.Decoder(InsertUser) {
  use name <- decode.field(0, decode.string)
  decode.success(InsertUser(name:))
}
